# Generated by Django 4.1.3 on 2022-11-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Company_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
